#!/usr/bin/env bash

# =====================================================
# setup_alias_c_windows.sh
# Tạo alias c / ckd / bo / kinh cho Git Bash Windows
# Repo tự nhận diện theo vị trí file setup hiện tại
# Ví dụ:
#   /f/ish_lang_nghiem/setup/setup_alias_c_windows.sh
# =====================================================

set -e

# Thư mục chứa file setup này
SETUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Repo là thư mục cha của setup/
REPO_DIR="$(cd "$SETUP_DIR/.." && pwd)"

COW_SCRIPT="$REPO_DIR/scripts/cow_kinh_dien.sh"
BASHRC="$HOME/.bashrc"

echo "🔧 Cài alias cow kinh điển cho Git Bash Windows..."
echo "Setup dir : $SETUP_DIR"
echo "Repo dir  : $REPO_DIR"
echo "Cow script: $COW_SCRIPT"
echo "Bashrc    : $BASHRC"

# Kiểm tra script cow
if [[ ! -f "$COW_SCRIPT" ]]; then
  echo "❌ Không tìm thấy script:"
  echo "   $COW_SCRIPT"
  exit 1
fi

# Kiểm tra file fortune
FORTUNE_FILE="$REPO_DIR/data/fortune_kinh_dien.txt"

if [[ ! -f "$FORTUNE_FILE" ]]; then
  echo "❌ Không tìm thấy file fortune:"
  echo "   $FORTUNE_FILE"
  exit 1
fi

# Cho phép thực thi
chmod +x "$COW_SCRIPT"

# Backup ~/.bashrc nếu có
if [[ -f "$BASHRC" ]]; then
  cp "$BASHRC" "$BASHRC.bak_cow_$(date +%Y%m%d_%H%M%S)"
  echo "✅ Đã backup ~/.bashrc"
fi

# Xóa block alias cũ nếu có
if [[ -f "$BASHRC" ]]; then
  sed -i '/# >>> ish_lang_nghiem cow aliases >>>/,/# <<< ish_lang_nghiem cow aliases <<</d' "$BASHRC"
fi

# Ghi block alias mới
cat >> "$BASHRC" <<EOF

# >>> ish_lang_nghiem cow aliases >>>
# Auto generated by setup_alias_c_windows.sh
export ISH_LANG_NGHIEM_REPO="$REPO_DIR"

alias c='bash "\$ISH_LANG_NGHIEM_REPO/scripts/cow_kinh_dien.sh"'
alias ckd='bash "\$ISH_LANG_NGHIEM_REPO/scripts/cow_kinh_dien.sh"'
alias bo='bash "\$ISH_LANG_NGHIEM_REPO/scripts/cow_kinh_dien.sh"'
alias kinh='bash "\$ISH_LANG_NGHIEM_REPO/scripts/cow_kinh_dien.sh"'
# <<< ish_lang_nghiem cow aliases <<<
EOF

echo
echo "✅ Đã cài alias vào: $BASHRC"
echo
echo "Các lệnh dùng được:"
echo "  c"
echo "  ckd"
echo "  bo"
echo "  kinh"
echo
echo "Nạp lại ngay bằng:"
echo "  source ~/.bashrc"
echo
echo "Test:"
echo "  c"
echo "  bo"