#!/usr/bin/env bash

# =====================================================
# setup_gitbash_windows.sh
# Cài ish_lang_nghiem cho Git Bash Windows
# Tự nhận diện repo theo vị trí file setup hiện tại
# Dùng được cho Windows nhiều ổ đĩa: C:, D:, F:...
# =====================================================

set -e

# ---- 1. Tự nhận diện thư mục setup và repo ----
SETUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SETUP_DIR/.." && pwd)"

BASHRC="$HOME/.bashrc"

LN_SCRIPT="$REPO_DIR/ln_lang_nghiem.bash"
COW_SCRIPT="$REPO_DIR/scripts/cow_kinh_dien.sh"
FORTUNE_FILE="$REPO_DIR/data/fortune_kinh_dien.txt"

echo "🔧 Cài đặt ish_lang_nghiem cho Git Bash Windows..."
echo "Setup dir : $SETUP_DIR"
echo "Repo dir  : $REPO_DIR"
echo "Bashrc    : $BASHRC"
echo

# ---- 2. Kiểm tra file cần thiết ----
if [[ ! -f "$LN_SCRIPT" ]]; then
  echo "❌ Không thấy file:"
  echo "   $LN_SCRIPT"
  echo
  echo "👉 Hãy chắc chắn file setup nằm trong:"
  echo "   ish_lang_nghiem/setup/setup_gitbash_windows.sh"
  exit 1
fi

if [[ ! -f "$COW_SCRIPT" ]]; then
  echo "⚠️ Không thấy cow script:"
  echo "   $COW_SCRIPT"
  echo "👉 Các lệnh c / bo / kinh sẽ chưa dùng được."
else
  chmod +x "$COW_SCRIPT"
fi

if [[ ! -f "$FORTUNE_FILE" ]]; then
  echo "⚠️ Không thấy file fortune:"
  echo "   $FORTUNE_FILE"
  echo "👉 Cow vẫn có thể lỗi nếu thiếu file này."
fi

# ---- 3. Backup ~/.bashrc cũ ----
if [[ -f "$BASHRC" ]]; then
  cp "$BASHRC" "$BASHRC.bak_$(date +%Y%m%d_%H%M%S)"
  echo "✅ Đã backup ~/.bashrc"
fi

# ---- 4. Xóa block cũ nếu có ----
if [[ -f "$BASHRC" ]]; then
  sed -i '/# >>> ish_lang_nghiem >>>/,/# <<< ish_lang_nghiem <<</d' "$BASHRC"
fi

# ---- 5. Ghi block mới vào ~/.bashrc ----
cat >> "$BASHRC" <<EOF

# >>> ish_lang_nghiem >>>
# Auto generated by setup_gitbash_windows.sh

export ISH_LANG_NGHIEM_REPO="$REPO_DIR"

ln() {
  bash "\$ISH_LANG_NGHIEM_REPO/ln_lang_nghiem.bash" "\$@"
}

lnk() {
  bash "\$ISH_LANG_NGHIEM_REPO/ln_lang_nghiem.bash" lnk "\$@"
}

add() {
  bash "\$ISH_LANG_NGHIEM_REPO/add.sh" "\$@"
}

add5() {
  if [[ -f "\$ISH_LANG_NGHIEM_REPO/add_5.sh" ]]; then
    bash "\$ISH_LANG_NGHIEM_REPO/add_5.sh" "\$@"
  else
    echo "Không thấy file: \$ISH_LANG_NGHIEM_REPO/add_5.sh"
  fi
}

add30() {
  if [[ -f "\$ISH_LANG_NGHIEM_REPO/add_30.sh" ]]; then
    bash "\$ISH_LANG_NGHIEM_REPO/add_30.sh" "\$@"
  else
    echo "Không thấy file: \$ISH_LANG_NGHIEM_REPO/add_30.sh"
  fi
}

alias c='bash "\$ISH_LANG_NGHIEM_REPO/scripts/cow_kinh_dien.sh"'
alias ckd='bash "\$ISH_LANG_NGHIEM_REPO/scripts/cow_kinh_dien.sh"'
alias bo='bash "\$ISH_LANG_NGHIEM_REPO/scripts/cow_kinh_dien.sh"'
alias kinh='bash "\$ISH_LANG_NGHIEM_REPO/scripts/cow_kinh_dien.sh"'

echo "ish_lang_nghiem repo: \$ISH_LANG_NGHIEM_REPO"
echo "Use: ln 13 | ln \"0*\" | lnk \"xá\" | c | bo | kinh"
# <<< ish_lang_nghiem <<<
EOF

echo
echo "✅ Cài đặt xong."
echo
echo "Chạy tiếp:"
echo "  source ~/.bashrc"
echo
echo "Test:"
echo "  cd \"$REPO_DIR\""
echo "  ln 3"
echo "  c"
echo "  bo"
echo "  kinh"